### ISSUE TITLE
Problem: test "the contents of bag-info.txt are translated to METS (if any)" is misleading

### ISSUE THREAD

**Issue by Jennoit** [artefactual-labs/testing-checklists#9]
See lines 3 and 4 in 'regression-testing-checklist.csv' (items 1.3 and 1.4)

1. Metadata cannot be checked because there are no contents in bag-info.txt 
2. Contents are described as being "translated" in 1.3 and "parsed" in 1.4.  Should use same word.
3. "The contents of bag-info.txt are parsed into METS (if any)" should read
"The contents of bag-info.txt (if any) are parsed into METS"
3a. Ideally, "The contents of bag-info.txt are parsed into METS (if any)" should have contents. See item 1.  The (if any) should then be removed.

**Comment by peterVG** [comment]
After further investigation we found that issue#1 (no contents in bag-info.txt) is due to the fact that the wrong sample data is listed in 1.3. The baginfo.txt for 'SampleTransfers/BagTransfer' does indeed only contain the defaults and no additional metadata. See https://github.com/artefactual/archivematica-sampledata/blob/6c0257b3fe6091da13a16458390d12bc718ecd5f/SampleTransfers/BagTransfer/bag-info.txt 
However, the baginfo.txt for 'SampleTransfers/UnzippedBag' does contain sample custom metadata (see https://github.com/artefactual/archivematica-sampledata/blob/master/SampleTransfers/UnzippedBag/bag-info.txt). AND it does map successfully to <mets:amdSec><mets:sourceMD ID="sourceMD_1"><mets:mdWrap MDTYPE="OTHER" OTHERMDTYPE="BagIt"> in the METS file. So this test passed on Xenial but requires the checklist to refer to the correct sampledata. Issue#2 & issue#3 as described by Jenn above still stand.

**Comment by peterVG** [comment]
Note: the same issue applies to 1.4. The sample data in _SampleTransfers/BagTransfer.zip_ 's bag-info.txt does not have any metadata to 'translate/parse' into the METS file. See https://github.com/artefactual/archivematica-sampledata/blob/master/SampleTransfers/BagTransfer.zip but there is in https://github.com/artefactual/archivematica-sampledata/blob/master/SampleTransfers/ZippedBag.zip The checklist needs to be updated to reflect the correct sampledata to use in this test.
